# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        cache: ~
        blog:
            quality: 75
            filters:
                thumbnail: { size: [750, 350], position: center, mode: outbound }
        advert:
            quality: 75
            filters:
                thumbnail: { size: [300, 260], position: center, mode: outbound }
        advert_sm:
            quality: 75
            filters:
                thumbnail: { size: [250, 300], position: center, mode: outbound }
        advert_lg:
            quality: 75
            filters:
                thumbnail: { size: [1000, 800], position: center, mode: outbound }
        reference:
            quality: 75
            filters:
                thumbnail: { size: [800, 600], position: center, mode: outbound }
