twig:
    file_name_pattern: '*.twig'
    globals:
        config: '@App\Manager\SettingsManager'
        categories: '@App\Manager\AdvertCategoryManager'

when@test:
    twig:
        strict_variables: true
