vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        settings:
            uri_prefix: '%app.path.settings%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.settings%'
        post:
            uri_prefix: '%app.path.post%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.post%'
        category:
            uri_prefix: '%app.path.category%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.category%'
        reference:
            uri_prefix: '%app.path.reference%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.reference%'
        carousel:
            uri_prefix: '%app.path.carousel%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.carousel%'


